server:
  port: 8082

bank:
  config-source: config-server-nativo
  peer-service: ms-transacciones

spring:
  datasource:
    url: jdbc:h2:file:./xyz/data/bankxyz;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: never

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      dependencia:
        sliding-window-size: 2
        minimum-number-of-calls: 1
        failure-rate-threshold: 50

logging:
  level:
    root: WARN
    com.banco.xyz: INFO
  file:
    name: evidencias/logs/ms-intereses.log
