server:
  port: 9000

spring:
  application:
    name: auth-server

bank:
  oauth:
    issuer: http://localhost:9000

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: WARN
    com.banco.xyz: INFO
