spring.application.name=xyz-bff

server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore/bff-keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bff-local

# Los canales no abren H2. Agregan respuestas llamando al backend por HTTP.
bank.backend.base-url=http://localhost:8090

logging.level.com.banco.xyz=INFO
logging.level.org.springframework.security=INFO
