package com.banco.xyz.transacciones;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import jakarta.annotation.PostConstruct;

@Component
public class SagaSchema {

	private final JdbcTemplate jdbc;

	public SagaSchema(JdbcTemplate jdbc) {
		this.jdbc = jdbc;
	}

	@PostConstruct
	void crear() {
		jdbc.execute("""
				CREATE TABLE IF NOT EXISTS retiros_saga (
				    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				    event_id VARCHAR(64) NOT NULL UNIQUE,
				    cuenta_id BIGINT NOT NULL,
				    monto DECIMAL(15, 2) NOT NULL,
				    estado VARCHAR(30) NOT NULL,
				    detalle VARCHAR(255),
				    simular_fallo BOOLEAN NOT NULL,
				    simular_duplicado BOOLEAN NOT NULL
				)
				""");
		jdbc.execute("""
				CREATE TABLE IF NOT EXISTS eventos_procesados (
				    event_id VARCHAR(80) PRIMARY KEY,
				    cola VARCHAR(80) NOT NULL
				)
				""");
	}
}
